### PR TITLE
chore: minor updates to SteadyStateDiff

### PR DESCRIPTION
**Pull request by avik-pal**
- changing to explicit imports, so that we can remove DiffEqBae once NonlinearSolveBase is ready
- `Rodas5` seems to give incorrect results on `get_du(integrator)` -- changed the tests at least temporarily to use `Tsit5`

### CODE REVIEW

**Comment by avik-pal** [comment]
```julia
julia> sol = solve(prob, DynamicSS(Rodas5()); abstol = 1e-9, reltol = 1e-9)
(integrator.u, integrator.uprev, t, get_du(integrator)) = ([0.00019998000133326593, 9.998000233313312e-9], [0.0, 0.0], 9.999999999999999e-5, [0.0, 0.0])
retcode: Terminated
Interpolation: specialized 4rd order "free" stiffness-aware interpolation
t: 2-element Vector{Float64}:
 0.0
 9.999999999999999e-5
u: 2-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [0.00019998000133326593, 9.998000233313312e-9]
retcode: Success
u: 2-element Vector{Float64}:
 0.00019998000133326593
 9.998000233313312e-9

julia> sol = solve(prob, DynamicSS(Tsit5()); abstol = 1e-9, reltol = 1e-9)
(integrator.u, integrator.uprev, t, get_du(integrator)) = ([0.00019998000133326663, 9.998000233313266e-9], [0.0, 0.0], 9.999999999999999e-5, [1.9996000399973335, 0.00019994000933233337])
(integrator.u, integrator.uprev, t, get_du(integrator)) = ([0.002197581773691028, 1.207341413014797e-6], [0.00019998000133326663, 9.998000233313266e-9], 0.0010999999999999998, [1.995604836452618, 0.002192752408038969])
```

@oscardssmith: Chris mentioned you might know what is going on here ("it must just be giving k1")

**Comment by avik-pal** [comment]
@ChrisRackauckas the SciMLSensitivity test failures you mentioned the other day, have the same issue.

```julia
function G(p)
    tmp_prob = remake(prob, u0 = convert.(eltype(p), prob.u0), p = p)
    sol = solve(tmp_prob, DynamicSS(Tsit5()); abstol = 1e-14, reltol = 1e-14)
    A = convert(Array, sol)
    g(A, p, nothing)
end
res1 = ForwardDiff.gradient(G, p)
res2 = Calculus.gradient(G, p)
```

^This fixes it (only changing the solver)

**Comment by oscardssmith** [comment]
does Rodas5P work?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/OrdinaryDiffEq.jl/blob/951df5da610e8fcfa2f4afde72e5e4a456f7677f/lib/OrdinaryDiffEqCore/src/integrators/integrator_interface.jl#L62 oh I know what caused this 😅

**Comment by avik-pal** [comment]
No `Rodas5P` doesn't work, `TRBDF2` does work

**Comment by oscardssmith** [comment]
@ChrisRackauckas shouldn't fsallast be an accurate derivative?

**Comment by ChrisRackauckas** [comment]
If it's an FSAL method https://github.com/SciML/OrdinaryDiffEq.jl/pull/2445

**Pull request merged**
